language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      env: SYSTEM=macports
    - os: osx
      osx_image: xcode7.1
      env: SYSTEM=macports
    - os: osx
      osx_image: beta-xcode6.1
      env: SYSTEM=macports

script:
  - make
  - eval `bash _build/$SYSTEM/x86_64/$SYSTEM/current/install.sh`
