language: generic

matrix:
  include:
    - os: osx
      env: SYSTEM=macports PACKAGE=ocaml VERSION=4.03
    - os: osx
      env: SYSTEM=macports PACKAGE=ocaml VERSION=4.02
    - os: osx
      env: SYSTEM=macports PACKAGE=ocaml VERSION=4.01
    - os: osx
      env: SYSTEM=macports PACKAGE=opam VERSION=1.2
    - os: osx
      env: SYSTEM=macports PACKAGE=camlp4 VERSION=4.03 INSTALL=no
    - os: osx
      env: SYSTEM=macports PACKAGE=camlp4 VERSION=4.02 INSTALL=no
    - os: osx
      env: SYSTEM=macports PACKAGE=camlp4 VERSION=4.01 INSTALL=no

script:
  - SUBDIRECTORY=`cat subdirectory`
  - DEPLOY_TIME=`cat timestamp`
  - 'echo "Deploy timestamp: $DEPLOY_TIME"'
  - 'echo "Subdirectory: $SUBDIRECTORY"'
  - PACKAGE_MANAGER_URL=https://aantron.github.io/binaries/$SUBDIRECTORY/$SYSTEM/x86_64/$SYSTEM/current/install.sh
  - PACKAGE_URL=https://aantron.github.io/binaries/$SUBDIRECTORY/$SYSTEM/x86_64/$PACKAGE/$VERSION/install.sh
  - '[ "$INSTALL" == "no" ] || eval `wget -q -O - $PACKAGE_MANAGER_URL | bash`'
  - '[ "$INSTALL" == "no" ] || wget -q -O - $PACKAGE_URL | bash'
  - ls
