-
  version: "test-{build}"

  shallow_clone: true

  install:
    - appveyor DownloadFile "https://raw.githubusercontent.com/Chris00/ocaml-appveyor/master/install_ocaml.cmd" -FileName "C:\install_ocaml.cmd"
    - C:\install_ocaml.cmd
    - cd "%APPVEYOR_BUILD_FOLDER%"

  build_script:
    - echo %LIB%
    - 'C:\Cygwin\bin\bash -lc "echo $LIB"'
    - SET FOO=BAR
    - echo %FOO%
    - 'C:\Cygwin\bin\bash -lc "echo $FOO"'
    - echo let () = print_endline "hello world" > foo.ml
    - ls
    - cat foo.ml
    - ocamlopt foo.ml
    - .\camlprog.exe
    - ls
