version: "cygwin-{build}"

shallow_clone: true

environment:
  matrix:
    - ARCH: x86
      CYGWIN: C:\Cygwin
      CYGSH: C:\Cygwin\bin\bash -lc
    # - ARCH: x86_64
    #   CYGWIN: C:\Cygwin64
    #   CYGSH: C:\Cygwin64\bin\bash -lc

build_script:
  - echo foo

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
