-
  branches:
    except:
      - deploy
      - /build-.*/

  version: "test-{build}"

  shallow_clone: true

  only_commits:
    files:
      - src/install/cygwin/**/*
      - src/install/mingw/**/*
      - src/test/*.ps1
      - src/util/build.sh
      - Makefile
      - appveyor.yml

  environment:
    matrix:
      - {SYSTEM: cygwin, ARCH: x86, COMPILER: 4.03}
      - {SYSTEM: cygwin, ARCH: x86, COMPILER: 4.02}
      - {SYSTEM: cygwin, ARCH: x86, COMPILER: 4.01}
      - {SYSTEM: cygwin, ARCH: x86_64, COMPILER: 4.03}
      - {SYSTEM: cygwin, ARCH: x86_64, COMPILER: 4.02}
      - {SYSTEM: mingw, ARCH: x86_64, COMPILER: 4.03}
      - {SYSTEM: msvc, ARCH: x86_64, COMPILER: 4.03}

  matrix:
    fast_finish: true

  install:
    - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64

  build_script:
    - C:\Cygwin64\bin\bash -lc "make -C /cygdrive/c/projects/binaries build"
    - ps: '& ".\src\test\$env:SYSTEM.ps1"'
    - ls

-
  branches:
    only:
      - deploy

  version: "deploy-{build}"

  shallow_clone: true

  environment:
    matrix:
      - {SYSTEM: cygwin, ARCH: x86, PACKAGE: flexdll, VERSION: 0.35}
      - {SYSTEM: cygwin, ARCH: x86_64, PACKAGE: flexdll, VERSION: 0.35}
      - {SYSTEM: cygwin, ARCH: x86, PACKAGE: ocaml, VERSION: 4.03}
      - {SYSTEM: cygwin, ARCH: x86, PACKAGE: ocaml, VERSION: 4.02}
      - {SYSTEM: cygwin, ARCH: x86, PACKAGE: ocaml, VERSION: 4.01}
      - {SYSTEM: cygwin, ARCH: x86_64, PACKAGE: ocaml, VERSION: 4.03}
      - {SYSTEM: cygwin, ARCH: x86_64, PACKAGE: ocaml, VERSION: 4.02}
      - {SYSTEM: cygwin, ARCH: x86, PACKAGE: opam, VERSION: 1.2}
      - {SYSTEM: cygwin, ARCH: x86, PACKAGE: camlp4, VERSION: 4.02, INSTALL: no}
      - {SYSTEM: cygwin, ARCH: x86, PACKAGE: camlp4, VERSION: 4.01, INSTALL: no}
      - {SYSTEM: mingw, ARCH: x86_64, PACKAGE: ocaml, VERSION: 4.03}
      - {SYSTEM: mingw, ARCH: x86_64, PACKAGE: opam, VERSION: 1.2, INSTALL: no}
      - {SYSTEM: mingw, ARCH: x86_64, PACKAGE: camlp4, VERSION: 4.03, INSTALL: no}

  matrix:
    fast_finish: true

  build_script:
    - SET /p SUBDIRECTORY=< subdirectory
    - SET /p DEPLOY_TIME=< timestamp
    - 'echo Commit timestamp: %APPVEYOR_REPO_COMMIT_TIMESTAMP%'
    - 'echo Deploy timestamp: %DEPLOY_TIME%'
    - 'echo Subdirectory: %SUBDIRECTORY%'
    - 'SET URL=https://aantron.github.io/binaries/%SUBDIRECTORY%/%SYSTEM%/%ARCH%/%PACKAGE%/%VERSION%/install.ps1'
    - ps: 'if ($env:INSTALL -eq "no") { (new-object net.webclient).DownloadString($env:URL) > $null } else { (new-object net.webclient).DownloadString($env:URL) | PowerShell -Command - }'
    - ls
